[workspace]
members = [
  "anyrun",
  "anyrun-plugin",
  "anyrun-interface",
  "plugins/applications",
  "plugins/symbols",
  "plugins/rink",
  "plugins/shell",
  "plugins/translate",
  "plugins/randr",
]